[package]
name = "sql_schema_fix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = { version = "*", features = [] }
clap = { version = "4", features = ["derive"] }
indexmap = "1"